KEYBOARD_SHORTCUTS:
- button: pushButton_ToggleFill
  callback: toggleFillButton
  shortcut: f
- button: pushButton_ToggleVisibility
  callback: onPushButton_ToggleVisibility
  shortcut: v
- button: pushButton_undo
  callback: onPushButton_undo
  shortcut: z
- button: SaveSegmentationButton
  callback: onSaveSegmentationButton
  shortcut: s
- button: pushButton_Smooth
  callback: onPushButton_Smooth
  shortcut: l
- button: pushButton_Small_holes
  callback: onPushButton_Small_holes
  shortcut: o
- button: pushButton_Interpolate
  callback: onPushButton_Interpolate
  shortcut: i
- button: SaveClassificationButton
  callback: onSaveClassificationButton
  shortcut: c
checkboxes:
  Craniectomy_checkbox: Craniectomy
  Craniotomy_checkbox: Craniotomy
  EVD_checkbox: EVD
  ICH_checkbox: ICH
  IVH_checkbox: IVH
  Infarct_checkbox: Infarct
  Intra_axial_tumor_checkbox: Intra-axial tumor
  Menigioma_checkbox: Meningioma
  Metal_artifact_checkbox: Metal artifact
  Midline_shift_checkbox: Midline shift
  Motion_artifact_checkbox: Motion artifact
  Multiple_lesions_checkbox: Multiple lesions
  Normal_checkbox: Normal
  Pressure_monitor_checkbox: Pressure monitor
  SAH_checkbox: SAH
  SDH_checkbox: SDH
  Tonsillar_herniation_checkbox: Tonsillar herniation
  test: Test
comboboxes:
  v01:
    atrophy:
      atrophy_mild: Mild
      atrophy_moderate: Moderate
      atrophy_none: None
      atrophy_severe: Severe
    ventricular_size:
      ventricular_size_mild: Mild
      ventricular_size_moderate: Moderate
      ventricular_size_normal: Normal/proportional
      ventricular_size_severe: Severe
    white_matter_changes:
      wmc_mild: Mild
      wmc_moderate: Moderate
      wmc_none: None
      wmc_severe: Severe
  v02:
    test:
      '22': '22'
      '222': '222'
    ventricular_size:
      ventricular_size_mild: Mild
      ventricular_size_moderate: Moderate
      ventricular_size_normal: Normal/proportional
      ventricular_size_severe: Severe
    white_matter_changes:
      wmc_mild: Mild
      wmc_moderate: Moderate
      wmc_none: None
      wmc_severe: Severe
  v03:
    test:
      '111': '111'
      '22': '22'
    ventricular_size:
      ventricular_size_mild: Mild
      ventricular_size_moderate: Moderate
      ventricular_size_normal: Normal/proportional
      ventricular_size_severe: Severe
    white_matter_changes:
      wmc_mild: Mild
      wmc_moderate: Moderate
      wmc_none: None
      wmc_severe: Severe
ct_window_level: 45
ct_window_width: 85
default_segmentation_directory: ''
default_volume_directory: ''
enable_debug: true
freetextboxes:
  number_of_focal_points: Number of focal points
  other_comments: Comments
impose_bids_format: false
input_filetype: '*.nii.gz'
interpolate_value: false
is_classification_requested: true
is_display_timer_requested: false
is_keyboard_shortcuts_requested: true
is_mouse_shortcuts_requested: true
is_segmentation_requested: true
is_semi_automatic_phe_tool_requested: true
keep_working_list: true
labels:
- color_b: 255
  color_g: 255
  color_r: 0
  lower_bound_HU: 30
  name: edema
  upper_bound_HU: 90
  value: 1
- color_b: 255
  color_g: 10
  color_r: 10
  lower_bound_HU: 30
  name: hemorrhage
  upper_bound_HU: 90
  value: 2
- color_b: 22
  color_g: 222
  color_r: 22
  lower_bound_HU: 30
  name: test_sc
  upper_bound_HU: 90
  value: 3
modality: MRI
remaining_list_filename: remaining_list.yaml
require_empty: false
save_uint8: true
slice_view_color: Yellow
working_list_filename: working_list.yaml
